### ISSUE TITLE
Allow player to set difficulty

### ISSUE THREAD

**Issue by bearlikelion** [bearlikelion/ah-hack#2]
Move the [difficulty](https://github.com/bearlikelion/ah-hack/blob/master/main.py#L10) code into the numGame.py file so we can reference it within the game instead of passing a parameter into the class to do so.

Allow the player to set the max # for the random to create the game's '*difficulty*'

**Comment by bearlikelion** [comment]
[Commited](https://github.com/bearlikelion/ah-hack/commit/4f681bac5a6d84a766d175b08a77b7d086b22989) changes for custom player difficulty. 

I created a [pull request](https://github.com/bearlikelion/ah-hack/pull/3) for review to accept these changes.

**Comment by bearlikelion** [comment]
@slowthisbirddown please review, approve, and merge the PR on Github

**Comment by slowthisbirddown** [comment]
Code moved. Working on setting up difficulty.
